#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd
#username
#user id
#Home directory path for the user

i=0
while [ $i -le 0 ];
do
        cut -d: -f 1,3,6 </etc/passwd 	
        ((i++))
done
