#!/usr/bin/env bash
#our Bash script should check if the file exists and print:
#if the file exists: school file exists
#if the file does not exist: school file does not exist

if [ -e school ]
then
    echo "school file exists"
    # check if file is empty
    if [ -s school ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    # check if file is a regular file
    if [ -f school ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
